baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ing. Jonathan Josafhat Ramírez Almazán"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 25 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "CV"
  facebook = ""
  twitter = "https://twitter.com/jonas227"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jonathan-josafhat-ramirez-almazan-005073138/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "static/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
