baseURL = "https://mycv2019.onrender.com"
languageCode = "en-us"
title = "¡Bienvenido!"
theme = "ananke"
#themesDir = "../.."


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Curioso"
  facebook = ""
  twitter = "https://twitter.com/jonas227"
  instagram = ""
  youtube = "https://www.youtube.com/"
  github = "https://github.com/JonasRA?tab=overview&from=2019-06-01&to=2019-06-30"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jonathan-josafhat-ramirez-almazan-005073138/"
  mastodon = "https://mastodon.social/web/accounts/857660"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/buildings-3703635_1280.jpg"
  recent_posts_number = 9